using System.Runtime.Serialization;

namespace WCPAPI
{
    [DataContract]
    public class Stats
    {
        [DataMember(Name = "health")]
        public int Health;
        [DataMember(Name = "powerType")]
        public string PowerType;
        [DataMember(Name = "power")]
        public int Power;
        [DataMember(Name = "str")]
        public int Strength;
        [DataMember(Name = "agi")]
        public int Agility;
        [DataMember(Name = "sta")]
        public int Stamina;
        [DataMember(Name="int")]
        public int Intellect;
        [DataMember(Name = "spr")]
        public int Spirit;
        [DataMember(Name = "attackPower")]
        public int AttackPower;
        [DataMember(Name = "rangedAttackPower")]
        public int RangedAttackPower;
        [DataMember(Name = "mastery")]
        public float Mastery;
        [DataMember(Name = "masteryRating")]
        public int MasteryRating;
        [DataMember(Name = "crit")]
        public float Crit;
        [DataMember(Name = "critRating")]
        public int CritRating;
        [DataMember(Name = "hitPercent")]
        public float HitPercent;
        [DataMember(Name = "hitRating")]
        public int HitRating;
        [DataMember(Name = "hasteRating")]
        public int HasteRating;
        [DataMember(Name = "expertiseRating")]
        public int ExpertiseRating;
        [DataMember(Name = "spellPower")]
        public int SpellPower;
        [DataMember(Name = "spellPen")]
        public int SpellPen;
        [DataMember(Name = "spellCrit")]
        public float SpellCrit;
        [DataMember(Name = "spellCritRating")]
        public int SpellCritRating;
        [DataMember(Name = "spellHitPercent")]
        public float SpellHitPercent;
        [DataMember(Name = "spellHitRating")]
        public int SpellHitRating;
        [DataMember(Name = "mana5")]
        public float Mana5;
        [DataMember(Name = "mana5Combat")]
        public float Mana5Combat;
        [DataMember(Name = "armor")]
        public int Armor;
        [DataMember(Name = "dodge")]
        public float Dodge;
        [DataMember(Name = "dodgeRating")]
        public int DodgeRating;
        [DataMember(Name = "parry")]
        public float Parry;
        [DataMember(Name = "parryRating")]
        public int ParryRating;
        [DataMember(Name = "block")]
        public float Block;
        [DataMember(Name = "blockRating")]
        public int BlockRating;
        [DataMember(Name = "resil")]
        public int Resilience;
        [DataMember(Name = "mainHandDmgMin")]
        public float MainHandDmgMin;
        [DataMember(Name = "mainHandDmgMax")]
        public float MainHandDmgMax;
        [DataMember(Name = "mainHandSpeed")]
        public float MainHandSpeed;
        [DataMember(Name = "mainHandDps")]
        public float MainHandDps;
        [DataMember(Name = "mainHandExpertise")]
        public int MainHandExpertise;
        [DataMember(Name = "offHandDmgMin")]
        public float OffHandDmgMin;
        [DataMember(Name = "offHandDmgMax")]
        public float OffHandDmgMax;
        [DataMember(Name = "offHandSpeed")]
        public float OffHandSpeed;
        [DataMember(Name = "offHandDps")]
        public float OffHandDps;
        [DataMember(Name = "offHandExpertise")]
        public int OffHandExpertise;
        [DataMember(Name = "rangedDmgMin")]
        public float RangedDmgMin;
        [DataMember(Name = "rangedDmgMax")]
        public float RangedDmgMax;
        [DataMember(Name = "rangedSpeed")]
        public float RangedSpeed;
        [DataMember(Name = "rangedDps")]
        public float RangedDps;
        [DataMember(Name = "rangedCrit")]
        public float RangedCrit;
        [DataMember(Name = "rangedCritRating")]
        public int RangedCritRating;
        [DataMember(Name = "rangedHitPercent")]
        public float RangedHitPercent;
        [DataMember(Name = "rangedHitRating")]
        public int RangedHitRating;
    }
}
